language: python

python:
  - "2.7"

branches:
  only:
    - master

install:
  - pip install -r requirements.txt
  - pip install coveralls

script: coverage run -m unittest discover

after_success:
  coveralls